version: '3.8'

services:
  # FastAPI Application
  fastapi_app:
    image: python:3.12-slim  # Use the official Python image
    container_name: fastapi_app
    working_dir: /app
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: /bin/sh -c "apt-get update && apt-get install -y build-essential cmake g++ libstdc++6 gcc && pip install --upgrade pip && pip install -r requirements.txt && uvicorn agent_researcher.main:app --host 0.0.0.0 --port 8000"
    environment:
      - PYTHONPATH=/app/src  # Set the PYTHONPATH to locate the modules
      - DATABASE_URL=postgresql://postgres:password@postgres_db:5432/mydatabase  # PostgreSQL connection string
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    depends_on:
      - postgres_db  # Ensure PostgreSQL starts before FastAPI
    networks:
      - app_network

  # PostgreSQL Database
  postgres_db:
    image: postgres:14  # Use the official PostgreSQL image
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres  # Username for the PostgreSQL database
      POSTGRES_PASSWORD: password  # Password for the PostgreSQL user
      POSTGRES_DB: mydatabase  # Name of the default database
    ports:
      - "5432:5432"  # Expose PostgreSQL port 5432 to the host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume for persistent PostgreSQL data
    networks:
      - app_network

# Volumes for persistent data storage
volumes:
  postgres_data:

# Docker network to allow communication between containers
networks:
  app_network: